### PR TITLE
sort download links in order to allow playback before all links are d…

### PR DESCRIPTION
**Pull request by jeffcunat**
…ownloaded

In our use case, we allow the playback during the downloading.
This PR orders the links to be downloaded in parallel over all representations in order to be able to switch from representations (ex audio languages).
Before this PR only the first audio track is downloaded, then the second one, etc...
Now segments are downloaded "in parallel" so we are able to switch from audio tracks during downloading

### CODE REVIEW

**Comment by mackode** [comment]
@jeffcunat Hey, this PR is really nice and clever for your use-case. 

1. I can see that PR contains upgrade of dependencies. Is this required change to fulfil the goal of PR? or we can remove it from PR and use master's configuration?

2. Actually, I can see that the PR change counts on the order of defining media in the manifest and not exactly by media type. Can you, instead of sorting, create 3 media buckets `video`, `audio`, `text`, push urls appropriately and after that `concat` these bucket into `links` e.g. in order text|audio|video? Is this make sense to you?

**Comment by jeffcunat** [comment]
1. Yes, no problem the dependencies are the master's one, the PR was created before. I am going to rebase it to be sync with the master

2. The idea of this PR is to download all media in parallel (in order to have the beginning of all types all at the same time). This way you can start playing a video, having all the audio channels and the text tracks even if everything is not loaded.
Here is an example of downloading before and after the PR
Before the PR  => video1 : 75%, audio1: 75%, audio2: 0%, audio3: 0%, text1: 75%, text2: 0%
After the PR => video1: 60%, audio1: 60%, audio2: 60%, audio3: 60%, text1: 60%, text2: 60%

Before we were not able to play and switch of audio or text tracks before the end of downloading
Now we are able to play the video and switch audio or text tracks as soon as we have enough data.

So if we concat video, audio, text buckets as you propose, we lose the benefit of sorting all links mixed together, we would download video first, then audio, then texts...

**Comment by mackode** [comment]
Yes, I understand the `parallel` downloads idea.

My concern is more about the `sort`ing thing, which relays on position in Manifest (index?).

Am I right that if I put `video` media at the end of Manifest it will not work as you expect? e.g. have a look at http://demo.unified-streaming.com/video/ateam/ateam.ism/ateam.mpd after applying `sort` we would download video first, then audio, then texts.

**Comment by jeffcunat** [comment]
sorry @mackode I'm back from holidays I don't get your point ... the index used for sorting requests is not the one of the media, it is the index inside the array of links (segmentInformation.mediaUrls) of a given type. The position of the video media inside the manifest does not matter. We are just sorting to get the first media links of all types first and not all video links, then all audio ones, then all text ones.

**Pull request merged**
